# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: openwrt-18.06
env:
  #REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_URL: https://github.com/openwrt/openwrt
  #REPO_BRANCH: master
  #CONFIG_FILE: .config
  #DIY_SH: diy.sh
  #FREE_UP_DISK: false
  SSH_ACTIONS: true
  #UPLOAD_BIN_DIR: false
  #UPLOAD_FIRMWARE: true 
#  pull_request:
#    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: OpenWrtCL
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
   #   - name: Checkout
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: SSH connection to Actions
#      uses: P3TERX/debugger-action@master
#      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'hello')

